package com.springapp.mvc.dao;

import com.springapp.mvc.domain.UserRedeemHistory;
import com.springapp.mvc.domain.UserRedeemHistoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserRedeemHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    int insert(UserRedeemHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    int insertSelective(UserRedeemHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    List<UserRedeemHistory> selectByExample(UserRedeemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    UserRedeemHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRedeemHistory record, @Param("example") UserRedeemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRedeemHistory record, @Param("example") UserRedeemHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRedeemHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_redeem_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRedeemHistory record);
}