package com.springapp.mvc.dao;

import com.springapp.mvc.domain.UserPointHistory;
import com.springapp.mvc.domain.UserPointHistoryExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("userPointHistoryMapper")
public interface UserPointHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    int insert(UserPointHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    int insertSelective(UserPointHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    List<UserPointHistory> selectByExample(UserPointHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    UserPointHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPointHistory record, @Param("example") UserPointHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPointHistory record, @Param("example") UserPointHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPointHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPointHistory record);
}