package com.springapp.mvc.dao;

import com.springapp.mvc.domain.UserPoint;
import com.springapp.mvc.domain.UserPointExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("userPointMapper")
public interface UserPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    int insert(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    int insertSelective(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    List<UserPoint> selectByExample(UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    UserPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPoint record, @Param("example") UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPoint record, @Param("example") UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserPoint record);
}