package com.springapp.mvc.domain;

import java.util.Date;

public class CouponPool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_pool.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_pool.coupon_id
     *
     * @mbggenerated
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_pool.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_pool.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_pool.id
     *
     * @return the value of coupon_pool.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_pool.id
     *
     * @param id the value for coupon_pool.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_pool.coupon_id
     *
     * @return the value of coupon_pool.coupon_id
     *
     * @mbggenerated
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_pool.coupon_id
     *
     * @param couponId the value for coupon_pool.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_pool.status
     *
     * @return the value of coupon_pool.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_pool.status
     *
     * @param status the value for coupon_pool.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_pool.date
     *
     * @return the value of coupon_pool.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_pool.date
     *
     * @param date the value for coupon_pool.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}