package com.springapp.mvc.domain;

import java.util.Date;

public class UserRedeemHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_redeem_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_redeem_history.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_redeem_history.coupon_id
     *
     * @mbggenerated
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_redeem_history.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_redeem_history.id
     *
     * @return the value of user_redeem_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_redeem_history.id
     *
     * @param id the value for user_redeem_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_redeem_history.user_id
     *
     * @return the value of user_redeem_history.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_redeem_history.user_id
     *
     * @param userId the value for user_redeem_history.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_redeem_history.coupon_id
     *
     * @return the value of user_redeem_history.coupon_id
     *
     * @mbggenerated
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_redeem_history.coupon_id
     *
     * @param couponId the value for user_redeem_history.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_redeem_history.date
     *
     * @return the value of user_redeem_history.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_redeem_history.date
     *
     * @param date the value for user_redeem_history.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}