package com.springapp.mvc.domain;

import java.util.Date;

public class UserPointHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_history.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_history.balance
     *
     * @mbggenerated
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_history.operate
     *
     * @mbggenerated
     */
    private Byte operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_history.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_history.id
     *
     * @return the value of user_point_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_history.id
     *
     * @param id the value for user_point_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_history.user_id
     *
     * @return the value of user_point_history.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_history.user_id
     *
     * @param userId the value for user_point_history.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_history.balance
     *
     * @return the value of user_point_history.balance
     *
     * @mbggenerated
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_history.balance
     *
     * @param balance the value for user_point_history.balance
     *
     * @mbggenerated
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_history.operate
     *
     * @return the value of user_point_history.operate
     *
     * @mbggenerated
     */
    public Byte getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_history.operate
     *
     * @param operate the value for user_point_history.operate
     *
     * @mbggenerated
     */
    public void setOperate(Byte operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_history.date
     *
     * @return the value of user_point_history.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_history.date
     *
     * @param date the value for user_point_history.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}